---
# The playbook for common tasks

- apt: update_cache=yes

- include: curl.yml tags=curl
- include: git.yml tags=git
- include: htop.yml tags=htop
- include: motd.yml tags=motd
- include: ntp.yml tags=ntp
- include: ssh.yml tags=ssh
